Loopy-fe/src/App.tsx, Loopy-fe/src/apis/kakao/address.ts, Loopy-fe/src/apis/kakao/interceptors.ts, Loopy-fe/src/apis/kakao/kakaoInstance.ts, Loopy-fe/src/assets/images/Destination.svg, Loopy-fe/src/assets/images/MapPin.svg, Loopy-fe/src/assets/images/Search.svg, Loopy-fe/src/components/button/SelectableButton.tsx, Loopy-fe/src/components/modal/LocationConsentModal.tsx, Loopy-fe/src/hooks/useSearchRegion.ts, Loopy-fe/src/pages/User/Login/_components/LoopyIconSection.tsx, Loopy-fe/src/pages/User/Login/index.tsx, Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx, Loopy-fe/src/pages/User/OnBoard/_components/StepLocationPermission.tsx, Loopy-fe/src/pages/User/OnBoard/_components/StepSearchArea.tsx, Loopy-fe/src/pages/User/OnBoard/index.tsx, Loopy-fe/src/pages/User/Signin/_components/CheckCircle.tsx, Loopy-fe/src/types/location.d.ts, Loopy-fe/src/utils/region.ts, Loopy-fe/src/vite-env.d.ts
=> Feat: login signup

Loopy-fe/src/components/button/SelectableButton.tsx, Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx, Loopy-fe/src/pages/User/OnBoard/index.tsx
=> Fix: recommend

Loopy-fe/src/components/Input/CommonInput.tsx, Loopy-fe/src/components/button/CommonButton.tsx, Loopy-fe/src/components/header/CommonHeader.tsx, Loopy-fe/src/pages/Admin/Login/index.tsx, Loopy-fe/src/pages/User/Login/_components/LoopyIconSection.tsx, Loopy-fe/src/pages/User/Login/_components/SocialLoginSection.tsx, Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx, Loopy-fe/src/pages/User/OnBoard/_components/search/CurrentLocationButton.tsx, Loopy-fe/src/pages/User/OnBoard/_components/search/SearchInputSection.tsx, Loopy-fe/src/pages/User/Signin/_components/AgreementItem.tsx, Loopy-fe/src/pages/User/Signin/_components/AgreementListView.tsx, Loopy-fe/src/pages/User/Signin/_components/CheckCircle.tsx, Loopy-fe/src/pages/User/Signin/_components/StepSignin/PasswordInput.tsx, Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepEmail.tsx, Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepVerify.tsx
=> Fix: font-login/signin

Loopy-fe/src/pages/User/Login/_components/LoopyIconSection.tsx
=> Fix: deploy_2

Loopy-fe/src/App.tsx, Loopy-fe/src/components/popup/CommonBottomPopup.tsx, Loopy-fe/src/pages/User/Challenge/mock/mockData.ts, Loopy-fe/src/pages/User/ChallengeDetail/ChallengeStoreListPage/index.tsx, Loopy-fe/src/pages/User/ChallengeDetail/components/SmallButton.tsx, Loopy-fe/src/pages/User/ChallengeDetail/index.tsx
- 챌린지 가능 매장 리스트 페이지 구현
- 팝업 공통 컴포넌트 등록 (노션 웹 페이지에 기록 완료)
=> Feat: challenge available cafe list

Loopy-fe/package.json, Loopy-fe/pnpm-lock.yaml, Loopy-fe/src/pages/User/Alarm/components/AlarmCard.tsx, Loopy-fe/src/pages/User/Alarm/index.tsx, Loopy-fe/src/pages/User/Alarm/mock/mockData.ts, Loopy-fe/src/pages/User/BookMark/index.tsx
=> Feat: bookmark_page, alarm_page

Loopy-fe/src/assets/images/Back.svg, Loopy-fe/src/components/header/CommonHeader.tsx
=> Fix: common-header

Loopy-fe/src/pages/User/My/Filter/index.tsx, Loopy-fe/src/pages/User/My/index.tsx
=> Feat: mypage-filterPage

Loopy-fe/src/components/card/CommonCard.tsx, Loopy-fe/src/pages/User/My/CouponBox/_components/CouponCard.tsx, Loopy-fe/src/pages/User/My/CouponBox/_mock/coupons.ts, Loopy-fe/src/pages/User/My/CouponBox/index.tsx, Loopy-fe/src/pages/User/My/index.tsx
=> Feat: mypage-coupon

Loopy-fe/src/hooks/Funnel/useFunnel.tsx, Loopy-fe/src/pages/User/My/Challenge/_components/ChallengeCard.tsx, Loopy-fe/src/pages/User/My/Challenge/index.tsx, Loopy-fe/src/pages/User/My/Challenge/mock/challenges.ts, Loopy-fe/src/pages/User/My/Challenge/types/challenges.ts, Loopy-fe/src/pages/User/My/index.tsx
> 마이페이지 챌린지 페이지 UI 구현
> 마이페이지 분기처리 및 리팩토링
=> Feat: mypage-challengepage

Loopy-fe/src/components/bottomBar/CommonBottomBar.tsx, Loopy-fe/src/components/popup/CommonBottomPopup.tsx, Loopy-fe/src/pages/User/My/Review/index.tsx, Loopy-fe/src/pages/User/My/index.tsx
=> Feat: mypage-review

Loopy-fe/package.json, Loopy-fe/pnpm-lock.yaml, Loopy-fe/src/components/input/SearchBar.tsx, Loopy-fe/src/pages/User/Map/_components/filter/FilterBar.tsx, Loopy-fe/src/pages/User/Map/index.tsx, Loopy-fe/src/pages/User/Search/index.tsx, Loopy-fe/tailwind.config.ts
> 스타일 수정 및 자잘한 수정, 헬멧 적용
pnpm add -D @types/react-helmet
=> Fix/map&detail 

Loopy-fe/src/assets/images/MapPin.svg, Loopy-fe/src/mock/stampHistoryDummy.ts, Loopy-fe/src/pages/User/My/StampExchange/_components/StampBookItem.tsx, Loopy-fe/src/pages/User/My/StampHistory/_components/StampHistoryItem.tsx, Loopy-fe/src/pages/User/My/StampHistory/index.tsx, Loopy-fe/src/pages/User/My/index.tsx, Loopy-fe/src/types/stampHistory.ts
=> Feat: stamphistory

Loopy-fe/src/apis/kakao/kakaoInstance.ts
=> Fix: js-key

Loopy-fe/src/pages/User/BookMark/index.tsx
=> Fix: bookmark

Loopy-fe/src/components/card/EventCard.tsx, Loopy-fe/src/components/input/SearchBar.tsx, Loopy-fe/src/pages/User/Detail/_components/ReviewButton.tsx, Loopy-fe/src/pages/User/Location/index.tsx, Loopy-fe/src/pages/User/Map/_components/filter/FilterDropdownButton.tsx, Loopy-fe/src/pages/User/Map/_components/filter/FilterIconButton.tsx, Loopy-fe/src/pages/User/Map/_components/filter/FilterPopup.tsx, Loopy-fe/src/pages/User/Map/index.tsx
=> Fix: image import

Loopy-fe/src/components/card/EventCard.tsx, Loopy-fe/src/pages/User/Map/_components/filter/FilterPopup.tsx
=> Fix: 파일 경로 수정

Loopy-fe/src/pages/User/Alarm/mock/mockData.ts, Loopy-fe/src/pages/User/Home/components/ExpireTag.tsx, Loopy-fe/src/pages/User/Home/components/MyStamp.tsx, Loopy-fe/src/pages/User/MyStamp/components/GetRemainingDays.ts, Loopy-fe/src/pages/User/MyStamp/index.tsx
=> Style: mystamp

Loopy-fe/src/assets/images/ArrowRight.svg, Loopy-fe/src/components/card/EventCard.tsx, Loopy-fe/src/mock/dummyReviews.ts, Loopy-fe/src/pages/User/Challenge/components/ChallengeCard.tsx, Loopy-fe/src/pages/User/Challenge/components/ChallengeTab.tsx, Loopy-fe/src/pages/User/Challenge/index.tsx, Loopy-fe/src/pages/User/My/Review/_components/ReviewImageSlider.tsx, Loopy-fe/src/pages/User/My/Review/_components/ReviewItem.tsx, Loopy-fe/src/pages/User/My/Review/index.tsx, Loopy-fe/src/pages/User/My/Skeleton/MainMypageSkeleton.tsx, Loopy-fe/src/pages/User/My/StampExchange/Skeleton/StampBookItemSkeleton.tsx, Loopy-fe/src/pages/User/My/StampExchange/index.tsx, Loopy-fe/src/pages/User/My/StampHistory/Skeleton/StampHistoryItemSkeleton.tsx, Loopy-fe/src/pages/User/My/StampHistory/index.tsx, Loopy-fe/src/pages/User/My/_components/MainMyPage.tsx, Loopy-fe/src/pages/User/My/index.tsx, Loopy-fe/src/pages/User/Review/index.tsx
> 리뷰 페이지 수정 및 구현
> 추가적인 수정 사항 업데이트
> skeleton UI 구현
closes #90 
closes #89 
closes #88 
closes #87 
> issue 참고.
=> Refactor: mypage

Loopy-fe/package.json, Loopy-fe/pnpm-lock.yaml, Loopy-fe/src/App.tsx, Loopy-fe/src/pages/User/OnBoard/index.tsx, Loopy-fe/src/store/useAuthStore.ts, Loopy-fe/src/utils/authCheck.ts, Loopy-fe/src/utils/crypto.ts, Loopy-fe/src/utils/storage.ts
> 로그인 api 연결을 위한 설정
> storage 생성
> zustand를 활용한 store 생성 -> 추가 수정 예정
=> Feat: token-storage

Loopy-fe/src/apis/axios.ts, Loopy-fe/src/apis/login/api.ts, Loopy-fe/src/apis/login/type.ts, Loopy-fe/src/apis/signin/api.ts, Loopy-fe/src/apis/signin/type.ts, Loopy-fe/src/apis/types/ApiResponse.ts, Loopy-fe/src/components/button/SelectableButton.tsx, Loopy-fe/src/components/input/CommonInput.tsx, Loopy-fe/src/hooks/action/useHandleLogin.ts, Loopy-fe/src/hooks/query/login/useLogin.ts, Loopy-fe/src/hooks/query/signin/useSignup.ts, Loopy-fe/src/pages/User/Login/index.tsx, Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepVerify.tsx, Loopy-fe/src/pages/User/Signin/_components/verify/PhoneInput.tsx, Loopy-fe/src/pages/User/Signin/_components/verify/SignupButton.tsx, Loopy-fe/src/pages/User/Signin/_components/verify/VeryfyCodeInput.tsx, Loopy-fe/src/utils/mapper.ts
> 로그인/회원가입 api 목데이터 연결
closes #92 
=> Api: login-signup [mocks connect]

Loopy-fe/src/App.tsx, Loopy-fe/src/apis/axios.ts, Loopy-fe/src/pages/User/Login/_components/SocialLoginSection.tsx, Loopy-fe/src/pages/auth/LoginSuccess.tsx
> 카카오 로그인 연결
https://github.com/user-attachments/assets/7db72797-b1a4-470a-a996-c7d83e11bf60
=> Api: kakao-login

Loopy-fe/src/apis/onboard/api.ts, Loopy-fe/src/apis/onboard/type.ts, Loopy-fe/src/hooks/query/onboard/usePreferredArea.ts, Loopy-fe/src/pages/User/OnBoard/_components/StepCafeInfo.tsx, Loopy-fe/src/pages/User/OnBoard/_components/StepSearchArea.tsx, Loopy-fe/src/pages/User/OnBoard/_components/TagSection.tsx
> onboard api mock 데이터 연결 [patch]
> onboard query 생성
#107 
=> Api: onboard [mock]

Loopy-fe/src/pages/User/My/StampExchange/_components/StampBookItem.tsx, Loopy-fe/src/pages/User/My/StampExchange/_components/StampDetailPage.tsx, Loopy-fe/src/pages/User/My/StampExchange/index.tsx, Loopy-fe/src/pages/User/MyStamp/components/StampPaper.tsx
=> Fix: mypage-stampbook

Loopy-fe/src/firebase/firebase-config.ts, Loopy-fe/src/pages/Admin/Signin/index.tsx, Loopy-fe/src/pages/User/My/Setting/_components/WithdrawAccountView.tsx, Loopy-fe/src/pages/User/My/index.tsx, Loopy-fe/src/pages/User/Signin/_components/AgreementListView.tsx, Loopy-fe/src/pages/User/Signin/_components/AgreementPage.tsx, Loopy-fe/src/pages/User/Signin/_components/verify/PhoneInput.tsx, Loopy-fe/src/pages/User/Signin/index.tsx, Loopy-fe/src/types/form.ts, Loopy-fe/src/utils/mapper.ts, Loopy-fe/src/vite-env.d.ts
=> Fix: signin

Loopy-fe/src/apis/alarm/api.ts, Loopy-fe/src/apis/stampBook/stampBookDetail/type.ts
=> Fix: api home

Loopy-fe/src/hooks/usePhoneVerification.ts, Loopy-fe/src/pages/User/Signin/_components/StepSignin/StepVerify.tsx
> sms-verify sms 인증 관련 인증 코드 올바르게 입력시 통과되도록 수정
closes #142 
=> Fix: sms-verify

Loopy-fe/src/pages/Admin/Signin/_components/AdminSignupButton.tsx, Loopy-fe/src/pages/Admin/Signin/_components/AdminStepPhoneVerify.tsx, Loopy-fe/src/pages/Admin/Signin/index.tsx, Loopy-fe/src/pages/auth/LoginSuccess.tsx
> 카카오 로그인 ->  fcm 토큰 발급 및 로그인
https://github.com/user-attachments/assets/9ee019d3-dc5b-43f8-b2b6-84a7d3670212
=> Api: kakao/fcm-patch

Loopy-fe/src/pages/auth/LoginSuccess.tsx
> 커밋할 때 빼먹은 파일입니다
커밋할 때 빼먹은 파일입니다
=> Fix: kakao

Loopy-fe/index.html, Loopy-fe/vite.config.ts
> 이미지 렌더링 문제
> ios 입력창, textarea 줌인 문제
*매디가 말씀하신 대로 기존에는 외부 사이트에서 이미지 링크 복사를 때왔기 때문에 기간이 만료됐거나 없어지는 등 동적으로 링크가 바뀌기 때문에 서버에서 보내주는 이미지면 다 뜰겁니다..! 
일단 최대한 안 뜨게만 추가 설정했어요.
iOS는 font-size가 16px보다 작으면 확대가 된다고 하네요. 그리고 확대 그걸 고정시키면 지도도 확대가 아예 안 된다고 합니다.
그래서 이 부분은 얘기해봐야 할 것 같아요..! 다행히도 16 이상이면 괜찮은 것 같아요
=> Fix: pwa-image/ios-zoom

Loopy-fe/src/apis/my/api.ts, Loopy-fe/src/apis/my/type.ts, Loopy-fe/src/hooks/query/my/useMyPoint.ts, Loopy-fe/src/pages/User/My/_components/ProfileSection.tsx
current point
transaction point
> current point api
> transaction point api
=> Api: points

Loopy-fe/src/apis/my/convertedStamp/api.ts, Loopy-fe/src/apis/my/convertedStamp/mock.ts, Loopy-fe/src/apis/my/convertedStamp/type.ts, Loopy-fe/src/components/admin/topBar/CommonTopBar.tsx, Loopy-fe/src/hooks/query/my/useConvertedStampBook.ts, Loopy-fe/src/index.css, Loopy-fe/src/layouts/AdminLayout.tsx, Loopy-fe/src/pages/Admin/Home/index.tsx, Loopy-fe/src/pages/User/My/StampExchange/index.tsx, Loopy-fe/src/pages/User/My/StampHistory/_components/StampHistoryItem.tsx, Loopy-fe/src/pages/User/My/StampHistory/index.tsx, Loopy-fe/src/types/stampHistory.ts
> admin-home 화면 레이아웃 수정
> 스타일 수정
> 홈화면 layout 구조 변경
closes #161 
=> Feat: admin-home

Loopy-fe/src/components/admin/topBar/CommonTopBar.tsx
> commonTabBar 조건부 수정
closes #166 
> 다른 페이지에도 tabBar 똑같이 사용하면 됨
=> Fix: commonTabBar

Loopy-fe/src/assets/images/Toggle.svg, Loopy-fe/src/pages/Admin/Coupon/_components/AddCouponButton.tsx, Loopy-fe/src/pages/Admin/Coupon/_components/CouponList.tsx, Loopy-fe/src/pages/Admin/Coupon/_components/FilterToggleButton.tsx, Loopy-fe/src/pages/Admin/Coupon/index.tsx
=> Style: admin/coupon

Loopy-fe/src/pages/User/My/MyReview/_components/ReviewImageSlider.tsx
=> Fix: imageToggle

Loopy-fe/src/pages/Admin/Signin/_components/AdminPasswordInput.tsx, Loopy-fe/src/pages/Admin/Signin/_components/AdminPhoneInput.tsx, Loopy-fe/src/pages/Admin/Signin/_components/AdminSignupButton.tsx, Loopy-fe/src/pages/Admin/Signin/_components/AdminSignupSuccess.tsx, Loopy-fe/src/pages/Admin/Signin/_components/AdminSinginPage.tsx, Loopy-fe/src/pages/Admin/Signin/_components/AdminStepPhoneVerify.tsx, Loopy-fe/src/pages/Admin/Signin/_components/AdminVerifyCodeInput.tsx, Loopy-fe/src/pages/Admin/Signin/index.tsx
> 사장님 페이지 signin 스타일 수정 및 api 연결
=> Fix: admin/signin

Loopy-fe/src/App.tsx, Loopy-fe/src/hooks/action/useAdminHandleLogin.tsx, Loopy-fe/src/pages/Admin/Login/_components/AdminSocialLogin.tsx, Loopy-fe/src/pages/Admin/Login/index.tsx
=> Style: admin/login signin

Loopy-fe/src/components/admin/modal/CommonTwoButtonModal.tsx, Loopy-fe/src/pages/Admin/Setting/_components/AdminManageAccount.tsx
> 모달 변경 및 logout api 연동
closes #182 
=> Feat: admin/logout

Loopy-fe/src/apis/auth/ownerDelete/api.ts, Loopy-fe/src/apis/auth/ownerDelete/type.ts, Loopy-fe/src/hooks/mutation/admin/withdraw/useOwnerWithdraw.ts, Loopy-fe/src/pages/Admin/Setting/_components/AdminWithdrawView.tsx
=> Api: admin/withdraw

Loopy-fe/src/apis/admin/challenge/available/api.ts, Loopy-fe/src/apis/admin/challenge/available/type.ts, Loopy-fe/src/apis/admin/challenge/detail/api.ts, Loopy-fe/src/apis/admin/challenge/detail/type.ts, Loopy-fe/src/apis/admin/challenge/in-progress/api.ts, Loopy-fe/src/apis/admin/challenge/in-progress/type.ts, Loopy-fe/src/apis/admin/challenge/join/api.ts, Loopy-fe/src/apis/admin/challenge/join/type.ts, Loopy-fe/src/apis/admin/challenge/past/api.ts, Loopy-fe/src/apis/admin/challenge/past/type.ts, Loopy-fe/src/apis/admin/challenge/statistics/api.ts, Loopy-fe/src/apis/admin/challenge/statistics/type.ts, Loopy-fe/src/hooks/query/admin/challenge/useAvailableChallenges.ts, Loopy-fe/src/hooks/query/admin/challenge/useChallengeDetail.ts, Loopy-fe/src/hooks/query/admin/challenge/useChallengeStatistics.ts, Loopy-fe/src/hooks/query/admin/challenge/useInProgressChallenges.ts, Loopy-fe/src/hooks/query/admin/challenge/useJoinChallenge.ts, Loopy-fe/src/hooks/query/admin/challenge/usePastChallenges.ts
- admin challenge 페이지 `api.ts` `type.ts` 파일 작성
- api 연결 쿼리 작성
=> Api: admin challenge
